services:
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    # Add Docker group to container. Be sure to set this in your environment
    # backend container will need access to the Docker socket to run containers
    # and to the host network to access the ROS master
    group_add:
      - "${DOCKER_GID}"
    user: "1000:1000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Mount Docker socket
      - /home/${USERNAME}/disk2/tmp/output:/home/${USERNAME}/tmp/output # Mount output directory
      - /media/carmaker/Backup/00rosbag_datasets:/media/carmaker/Backup/00rosbag_datasets # Mount rosbags directory
      - /media/carmaker/Backup/00rosbag_datasets/rosbag_metadata.db:/app/data/rosbag_metadata.db

    restart: unless-stopped
    environment:
      - USERNAME=carmaker
      - USER_UID=1000
      - USER_GID=1000
      - DATABASE_PATH=/app/data/rosbag_metadata.db
    network_mode: host

  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    ports:
      - "5173:5173"
    restart: unless-stopped
    depends_on:
      - backend
